version: '2'

services:

  registry-svc:
    image: microservices-experiments/registry:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"

  gateway-svc:
    image: microservices-experiments/gateway:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - registry-svc
      - rest-svc-1
      - rest-svc-2
      - rest-svc-3

  rest-svc-1:
    image: microservices-experiments/service:0.0.1-SNAPSHOT
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - registry-svc

  rest-svc-2:
    image: microservices-experiments/service:0.0.1-SNAPSHOT
    environment:
      - SERVER_PORT=8082
    ports:
      - "8082:8082"
    depends_on:
      - registry-svc

  rest-svc-3:
    image: microservices-experiments/service:0.0.1-SNAPSHOT
    environment:
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
    depends_on:
      - registry-svc