spring:
  application:
    name: rest-service

server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-svc1:8761/eureka/,http://registry-svc2:8762/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true