spring:
  application:
    name: gateway

server:
  port: ${SERVER_PORT:8080}

zuul:
  routes:
    math:
      path: /rest/**
      serviceId: rest-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-svc:8761/eureka/
    registerWithEureka: false